### ISSUE TITLE
discover fails

### ISSUE THREAD

**Issue by legrostdg** [pimutils/vdirsyncer#448]
Using 
- vdirsyncer, version 0.10.1.dev40+ng45cea8f
- Python 3.5.1+
- debian sid
- (radicale 1.1.1-1)

and this config file:

    [general]
    status_path = ~/.vdirsyncer/status/
    
    [pair my_contacts]
    a = my_contacts_local
    b = my_contacts_remote
    collections = ["from a", "from b"]
    conflict_resolution = "a wins"
    
    [storage my_contacts_local]
    type = filesystem
    path = ~/.contacts/
    fileext = .vcf
    
    [storage my_contacts_remote]
    type = carddav
    url = https://dav.example.com/user/addressbook.vcf/
    username = user
    password = ************
    
    [pair my_calendars]
    a = calendars_local
    b = calendars_remote
    collections = ["from b", "from a"]
    conflict_resolution = "a wins"
    
    [storage calendars_local]
    type = filesystem
    path = ~/.calendars/
    fileext = .ics
    
    [storage calendars_remote]
    type = caldav
    url = https://dav.example.com/user/calendar.ics/
    username = user
    password = ************

I get:

    $ vdirsyncer -vdebug discover
    debug: Using 1 maximal workers.
    Discovering collections for pair my_contacts
    debug: PROPFIND https://dav.example.com/user/addressbook.vcf/
    debug: {'Content-Type': 'application/xml; charset=UTF-8', 'User-Agent': 'vdirsyncer', 'Depth': 0}
    debug: 
    debug:         <d:propfind xmlns:d="DAV:">
    debug:             <d:prop>
    debug:                 <d:current-user-principal />
    debug:             </d:prop>
    debug:         </d:propfind>
    debug:         
    debug: Sending request...
    debug: 207
    debug: {'Content-Length': '327', 'Content-Type': 'text/xml', 'Connection': 'keep-alive', 'Server': 'nginx/1.6.2', 'DAV': '1, 2, 3, calendar-access, addressbook, extended-mkcol', 'Date': 'Thu, 12 May 2016 13:33:35 GMT'}
    debug: b'<?xml version="1.0"?>\n<multistatus xmlns="DAV:">\n  <response>\n    <href>/user/addressbook.vcf/</href>\n    <propstat>\n      <prop>\n        <current-user-principal>\n          <href>/user/</href>\n        </current-user-principal>\n      </prop>\n      <status>HTTP/1.1 200 OK</status>\n    </propstat>\n  </response>\n</multistatus>\n'
    debug: PROPFIND https://dav.example.com/user/
    debug: {'Content-Type': 'application/xml; charset=UTF-8', 'User-Agent': 'vdirsyncer', 'Depth': 0}
    debug: 
    debug:     <d:propfind xmlns:d="DAV:" xmlns:c="urn:ietf:params:xml:ns:carddav">
    debug:         <d:prop>
    debug:             <c:addressbook-home-set />
    debug:         </d:prop>
    debug:     </d:propfind>
    debug:     
    debug: Sending request...
    debug: 207
    debug: {'Content-Length': '50', 'Content-Type': 'text/xml', 'Connection': 'keep-alive', 'Server': 'nginx/1.6.2', 'DAV': '1, 2, 3, calendar-access, addressbook, extended-mkcol', 'Date': 'Thu, 12 May 2016 13:33:37 GMT'}
    debug: b'<?xml version="1.0"?>\n<multistatus xmlns="DAV:" />'
    Unhandled exception occured.
    Traceback (most recent call last):
      File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev40+ng45cea8f-py3.5.egg/vdirsyncer/cli/utils.py", line 489, in _worker
        func(wq=self)
      File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev40+ng45cea8f-py3.5.egg/vdirsyncer/cli/tasks.py", line 77, in discover_collections
        rv = collections_for_pair(pair=pair, **kwargs)
      File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev40+ng45cea8f-py3.5.egg/vdirsyncer/cli/utils.py", line 192, in collections_for_pair
        list_collections=list_collections))
      File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev40+ng45cea8f-py3.5.egg/vdirsyncer/cli/utils.py", line 304, in _collections_for_pair_impl
        b_discovered = _discover_from_config(pair.config_b)
      File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev40+ng45cea8f-py3.5.egg/vdirsyncer/cli/utils.py", line 243, in _discover_from_config
        return handle_storage_init_error(cls, config)
      File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev40+ng45cea8f-py3.5.egg/vdirsyncer/cli/utils.py", line 235, in _discover_from_config
        discovered = list(cls.discover(**config))
      File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev40+ng45cea8f-py3.5.egg/vdirsyncer/storage/dav.py", line 202, in discover
        for c in self.find_collections():
      File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev40+ng45cea8f-py3.5.egg/vdirsyncer/storage/dav.py", line 181, in find_collections
        url = self.find_home()
      File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev40+ng45cea8f-py3.5.egg/vdirsyncer/storage/dav.py", line 176, in find_home
        raise InvalidXMLResponse()
    vdirsyncer.storage.dav.InvalidXMLResponse
    Discovering collections for pair my_calendars
    debug: PROPFIND https://dav.example.com/user/calendar.ics/
    debug: {'Content-Type': 'application/xml; charset=UTF-8', 'User-Agent': 'vdirsyncer', 'Depth': 0}
    debug: 
    debug:         <d:propfind xmlns:d="DAV:">
    debug:             <d:prop>
    debug:                 <d:current-user-principal />
    debug:             </d:prop>
    debug:         </d:propfind>
    debug:         
    debug: Sending request...
    debug: 207
    debug: {'Content-Length': '324', 'Content-Type': 'text/xml', 'Connection': 'keep-alive', 'Server': 'nginx/1.6.2', 'DAV': '1, 2, 3, calendar-access, addressbook, extended-mkcol', 'Date': 'Thu, 12 May 2016 13:33:40 GMT'}
    debug: b'<?xml version="1.0"?>\n<multistatus xmlns="DAV:">\n  <response>\n    <href>/user/calendar.ics/</href>\n    <propstat>\n      <prop>\n        <current-user-principal>\n          <href>/user/</href>\n        </current-user-principal>\n      </prop>\n      <status>HTTP/1.1 200 OK</status>\n    </propstat>\n  </response>\n</multistatus>\n'
    debug: PROPFIND https://dav.example.com/user/
    debug: {'Content-Type': 'application/xml; charset=UTF-8', 'User-Agent': 'vdirsyncer', 'Depth': 0}
    debug: 
    debug:     <d:propfind xmlns:d="DAV:" xmlns:c="urn:ietf:params:xml:ns:caldav">
    debug:         <d:prop>
    debug:             <c:calendar-home-set />
    debug:         </d:prop>
    debug:     </d:propfind>
    debug:     
    debug: Sending request...
    debug: 207
    debug: {'Content-Length': '50', 'Content-Type': 'text/xml', 'Connection': 'keep-alive', 'Server': 'nginx/1.6.2', 'DAV': '1, 2, 3, calendar-access, addressbook, extended-mkcol', 'Date': 'Thu, 12 May 2016 13:33:41 GMT'}
    debug: b'<?xml version="1.0"?>\n<multistatus xmlns="DAV:" />'
    Unhandled exception occured.
    Traceback (most recent call last):
      File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev40+ng45cea8f-py3.5.egg/vdirsyncer/cli/utils.py", line 489, in _worker
        func(wq=self)
      File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev40+ng45cea8f-py3.5.egg/vdirsyncer/cli/tasks.py", line 77, in discover_collections
        rv = collections_for_pair(pair=pair, **kwargs)
      File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev40+ng45cea8f-py3.5.egg/vdirsyncer/cli/utils.py", line 192, in collections_for_pair
        list_collections=list_collections))
      File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev40+ng45cea8f-py3.5.egg/vdirsyncer/cli/utils.py", line 304, in _collections_for_pair_impl
        b_discovered = _discover_from_config(pair.config_b)
      File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev40+ng45cea8f-py3.5.egg/vdirsyncer/cli/utils.py", line 243, in _discover_from_config
        return handle_storage_init_error(cls, config)
      File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev40+ng45cea8f-py3.5.egg/vdirsyncer/cli/utils.py", line 235, in _discover_from_config
        discovered = list(cls.discover(**config))
      File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev40+ng45cea8f-py3.5.egg/vdirsyncer/storage/dav.py", line 202, in discover
        for c in self.find_collections():
      File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev40+ng45cea8f-py3.5.egg/vdirsyncer/storage/dav.py", line 181, in find_collections
        url = self.find_home()
      File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev40+ng45cea8f-py3.5.egg/vdirsyncer/storage/dav.py", line 176, in find_home
        raise InvalidXMLResponse()
    vdirsyncer.storage.dav.InvalidXMLResponse
    error: 2 out of 2 tasks failed.

**Comment by untitaker** [comment]
This is a Radicale bug, cc @lize

Which was the last version that worked?

**Comment by untitaker** [comment]
In particular, this:

    b'<?xml version="1.0"?>\n<multistatus xmlns="DAV:" />'

as a response to a `calendar-home-set` query to `https://dav.example.com/user/` is invalid.

**Comment by legrostdg** [comment]
I guess that never worked perfectly... I'll report a bug in radicale, but I still think vdirsyncer should have a better error message. This "Unhandled exception occured." is not the best thing to return...

**Comment by untitaker** [comment]
I agree on that

**Comment by untitaker** [comment]
I pushed a commit that should make the error messsage remarkably nicer.

**Comment by untitaker** [comment]
Nevermind, this is actually an issue that is not new to Radicale version 1.1.1, and is a rather fundamental problem. Version 2.0 will fix this.

I'll try to include a workaround for Radicale in vdirsyncer.

**Comment by untitaker** [comment]
**actually**, I can't reproduce the particular bug you're experiencing, and from Radicale's sourcecode I can't figure out how you would end up with that response either.

**Comment by legrostdg** [comment]
mmh, I guess something changed on vdirsyncer side (I didn't updated radicale). The error is different now (notice that the error still looks ugly, more exception catching should probably be added :-)):

    debug: Using 1 maximal workers.
    Discovering collections for pair my_calendars
    debug: PROPFIND https://dav.example.com/user/calendar.ics/
    debug: {'Content-Type': 'application/xml; charset=UTF-8', 'User-Agent': 'vdirsyncer', 'Depth': 0}
    debug: 
    debug:         <d:propfind xmlns:d="DAV:">
    debug:             <d:prop>
    debug:                 <d:current-user-principal />
    debug:             </d:prop>
    debug:         </d:propfind>
    debug:         
    debug: Sending request...
    debug: 403
    debug: {'Connection': 'keep-alive', 'Content-Type': 'text/html', 'Date': 'Sun, 15 May 2016 08:53:45 GMT', 'Server': 'nginx/1.6.2', 'Content-Encoding': 'gzip', 'Transfer-Encoding': 'chunked', 'Vary': 'Accept-Encoding'}
    debug: b'<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body bgcolor="white">\r\n<center><h1>403 Forbidden</h1></center>\r\n<hr><center>nginx/1.6.2</center>\r\n</body>\r\n</html>\r\n'
    debug: GET https://dav.example.com/.well-known/caldav/
    debug: {'Content-Type': 'application/xml; charset=UTF-8', 'User-Agent': 'vdirsyncer'}
    debug: None
    debug: Sending request...
    debug: 404
    debug: {'Connection': 'keep-alive', 'Content-Type': 'text/html', 'Date': 'Sun, 15 May 2016 08:53:45 GMT', 'Server': 'nginx/1.6.2', 'Content-Encoding': 'gzip', 'Transfer-Encoding': 'chunked', 'Vary': 'Accept-Encoding'}
    debug: b'<html>\r\n<head><title>404 Not Found</title></head>\r\n<body bgcolor="white">\r\n<center><h1>404 Not Found</h1></center>\r\n<hr><center>nginx/1.6.2</center>\r\n</body>\r\n</html>\r\n'
    debug: Server does not support well-known URIs.
    debug: PROPFIND https://dav.example.com/user/calendar.ics/
    debug: {'Content-Type': 'application/xml; charset=UTF-8', 'User-Agent': 'vdirsyncer', 'Depth': 0}
    debug: 
    debug:         <d:propfind xmlns:d="DAV:">
    debug:             <d:prop>
    debug:                 <d:current-user-principal />
    debug:             </d:prop>
    debug:         </d:propfind>
    debug:         
    debug: Sending request...
    debug: 403
    debug: {'Connection': 'keep-alive', 'Content-Type': 'text/html', 'Date': 'Sun, 15 May 2016 08:53:45 GMT', 'Server': 'nginx/1.6.2', 'Content-Encoding': 'gzip', 'Transfer-Encoding': 'chunked', 'Vary': 'Accept-Encoding'}
    debug: b'<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body bgcolor="white">\r\n<center><h1>403 Forbidden</h1></center>\r\n<hr><center>nginx/1.6.2</center>\r\n</body>\r\n</html>\r\n'
    Unhandled exception occured.
    Traceback (most recent call last):
      File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev48+ng139182e-py3.5.egg/vdirsyncer/storage/dav.py", line 142, in find_principal
        return self.find_principal('')
      File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev48+ng139182e-py3.5.egg/vdirsyncer/storage/dav.py", line 156, in find_principal
        data=body)
      File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev48+ng139182e-py3.5.egg/vdirsyncer/storage/dav.py", line 324, in request
        return utils.http.request(method, url, session=self._session, **more)
      File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev48+ng139182e-py3.5.egg/vdirsyncer/utils/http.py", line 74, in request
        r.raise_for_status()
      File "/usr/lib/python3/dist-packages/requests/models.py", line 840, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://dav.example.com/user/calendar.ics/
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev48+ng139182e-py3.5.egg/vdirsyncer/cli/utils.py", line 498, in _worker
        func(wq=self)
      File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev48+ng139182e-py3.5.egg/vdirsyncer/cli/tasks.py", line 77, in discover_collections
        rv = collections_for_pair(pair=pair, **kwargs)
      File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev48+ng139182e-py3.5.egg/vdirsyncer/cli/utils.py", line 201, in collections_for_pair
        list_collections=list_collections))
      File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev48+ng139182e-py3.5.egg/vdirsyncer/cli/utils.py", line 313, in _collections_for_pair_impl
        b_discovered = _discover_from_config(pair.config_b)
      File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev48+ng139182e-py3.5.egg/vdirsyncer/cli/utils.py", line 252, in _discover_from_config
        return handle_storage_init_error(cls, config)
      File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev48+ng139182e-py3.5.egg/vdirsyncer/cli/utils.py", line 244, in _discover_from_config
        discovered = list(cls.discover(**config))
      File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev48+ng139182e-py3.5.egg/vdirsyncer/storage/dav.py", line 202, in discover
        for c in self.find_collections():
      File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev48+ng139182e-py3.5.egg/vdirsyncer/storage/dav.py", line 181, in find_collections
        url = self.find_home()
      File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev48+ng139182e-py3.5.egg/vdirsyncer/storage/dav.py", line 165, in find_home
        url = self.find_principal()
      File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev48+ng139182e-py3.5.egg/vdirsyncer/storage/dav.py", line 144, in find_principal
        return self.find_principal(self.find_dav())
      File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev48+ng139182e-py3.5.egg/vdirsyncer/storage/dav.py", line 156, in find_principal
        data=body)
      File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev48+ng139182e-py3.5.egg/vdirsyncer/storage/dav.py", line 324, in request
        return utils.http.request(method, url, session=self._session, **more)
      File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev48+ng139182e-py3.5.egg/vdirsyncer/utils/http.py", line 74, in request
        r.raise_for_status()
      File "/usr/lib/python3/dist-packages/requests/models.py", line 840, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://dav.example.com/user/calendar.ics/
    Discovering collections for pair my_contacts
    debug: PROPFIND https://dav.example.com/user/addressbook.vcf/
    debug: {'Content-Type': 'application/xml; charset=UTF-8', 'User-Agent': 'vdirsyncer', 'Depth': 0}
    debug: 
    debug:         <d:propfind xmlns:d="DAV:">
    debug:             <d:prop>
    debug:                 <d:current-user-principal />
    debug:             </d:prop>
    debug:         </d:propfind>
    debug:         
    debug: Sending request...
    debug: 403
    debug: {'Connection': 'keep-alive', 'Content-Type': 'text/html', 'Date': 'Sun, 15 May 2016 08:53:45 GMT', 'Server': 'nginx/1.6.2', 'Content-Encoding': 'gzip', 'Transfer-Encoding': 'chunked', 'Vary': 'Accept-Encoding'}
    debug: b'<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body bgcolor="white">\r\n<center><h1>403 Forbidden</h1></center>\r\n<hr><center>nginx/1.6.2</center>\r\n</body>\r\n</html>\r\n'
    debug: GET https://dav.example.com/.well-known/carddav/
    debug: {'Content-Type': 'application/xml; charset=UTF-8', 'User-Agent': 'vdirsyncer'}
    debug: None
    debug: Sending request...
    debug: 404
    debug: {'Connection': 'keep-alive', 'Content-Type': 'text/html', 'Date': 'Sun, 15 May 2016 08:53:45 GMT', 'Server': 'nginx/1.6.2', 'Content-Encoding': 'gzip', 'Transfer-Encoding': 'chunked', 'Vary': 'Accept-Encoding'}
    debug: b'<html>\r\n<head><title>404 Not Found</title></head>\r\n<body bgcolor="white">\r\n<center><h1>404 Not Found</h1></center>\r\n<hr><center>nginx/1.6.2</center>\r\n</body>\r\n</html>\r\n'
    debug: Server does not support well-known URIs.
    debug: PROPFIND https://dav.example.com/user/addressbook.vcf/
    debug: {'Content-Type': 'application/xml; charset=UTF-8', 'User-Agent': 'vdirsyncer', 'Depth': 0}
    debug: 
    debug:         <d:propfind xmlns:d="DAV:">
    debug:             <d:prop>
    debug:                 <d:current-user-principal />
    debug:             </d:prop>
    debug:         </d:propfind>
    debug:         
    debug: Sending request...
    debug: 403
    debug: {'Connection': 'keep-alive', 'Content-Type': 'text/html', 'Date': 'Sun, 15 May 2016 08:53:45 GMT', 'Server': 'nginx/1.6.2', 'Content-Encoding': 'gzip', 'Transfer-Encoding': 'chunked', 'Vary': 'Accept-Encoding'}
    debug: b'<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body bgcolor="white">\r\n<center><h1>403 Forbidden</h1></center>\r\n<hr><center>nginx/1.6.2</center>\r\n</body>\r\n</html>\r\n'
    Unhandled exception occured.
    Traceback (most recent call last):
      File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev48+ng139182e-py3.5.egg/vdirsyncer/storage/dav.py", line 142, in find_principal
        return self.find_principal('')
      File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev48+ng139182e-py3.5.egg/vdirsyncer/storage/dav.py", line 156, in find_principal
        data=body)
      File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev48+ng139182e-py3.5.egg/vdirsyncer/storage/dav.py", line 324, in request
        return utils.http.request(method, url, session=self._session, **more)
      File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev48+ng139182e-py3.5.egg/vdirsyncer/utils/http.py", line 74, in request
        r.raise_for_status()
      File "/usr/lib/python3/dist-packages/requests/models.py", line 840, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://dav.example.com/user/addressbook.vcf/
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev48+ng139182e-py3.5.egg/vdirsyncer/cli/utils.py", line 498, in _worker
        func(wq=self)
      File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev48+ng139182e-py3.5.egg/vdirsyncer/cli/tasks.py", line 77, in discover_collections
        rv = collections_for_pair(pair=pair, **kwargs)
      File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev48+ng139182e-py3.5.egg/vdirsyncer/cli/utils.py", line 201, in collections_for_pair
        list_collections=list_collections))
      File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev48+ng139182e-py3.5.egg/vdirsyncer/cli/utils.py", line 313, in _collections_for_pair_impl
        b_discovered = _discover_from_config(pair.config_b)
      File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev48+ng139182e-py3.5.egg/vdirsyncer/cli/utils.py", line 252, in _discover_from_config
        return handle_storage_init_error(cls, config)
      File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev48+ng139182e-py3.5.egg/vdirsyncer/cli/utils.py", line 244, in _discover_from_config
        discovered = list(cls.discover(**config))
      File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev48+ng139182e-py3.5.egg/vdirsyncer/storage/dav.py", line 202, in discover
        for c in self.find_collections():
      File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev48+ng139182e-py3.5.egg/vdirsyncer/storage/dav.py", line 181, in find_collections
        url = self.find_home()
      File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev48+ng139182e-py3.5.egg/vdirsyncer/storage/dav.py", line 165, in find_home
        url = self.find_principal()
      File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev48+ng139182e-py3.5.egg/vdirsyncer/storage/dav.py", line 144, in find_principal
        return self.find_principal(self.find_dav())
      File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev48+ng139182e-py3.5.egg/vdirsyncer/storage/dav.py", line 156, in find_principal
        data=body)
      File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev48+ng139182e-py3.5.egg/vdirsyncer/storage/dav.py", line 324, in request
        return utils.http.request(method, url, session=self._session, **more)
      File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev48+ng139182e-py3.5.egg/vdirsyncer/utils/http.py", line 74, in request
        r.raise_for_status()
      File "/usr/lib/python3/dist-packages/requests/models.py", line 840, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://dav.example.com/user/addressbook.vcf/
    error: 2 out of 2 tasks failed.

**Comment by untitaker** [comment]
I don't understand. Did you update vdirsyncer? From the error message it just seems that you don't have the proper credentials set, but that doesn't seem right either. I recommend removing the last path segment from the URL BTW, such that only the user is in the path.

I will have a look later, but can't promise much.

On 15 May 2016 10:56:14 CEST, legrostdg <notifications@github.com> wrote:
>mmh, I guess something changed on vdirsyncer side (I didn't updated
>radicale). The error is different now (notice that the error still
>looks ugly, more exception catching should probably be added :-)):
>
>    debug: Using 1 maximal workers.
>    Discovering collections for pair my_calendars
>    debug: PROPFIND https://dav.example.com/user/calendar.ics/
>debug: {'Content-Type': 'application/xml; charset=UTF-8', 'User-Agent':
>'vdirsyncer', 'Depth': 0}
>    debug: 
>    debug:         <d:propfind xmlns:d="DAV:">
>    debug:             <d:prop>
>    debug:                 <d:current-user-principal />
>    debug:             </d:prop>
>    debug:         </d:propfind>
>    debug:         
>    debug: Sending request...
>    debug: 403
>debug: {'Connection': 'keep-alive', 'Content-Type': 'text/html',
>'Date': 'Sun, 15 May 2016 08:53:45 GMT', 'Server': 'nginx/1.6.2',
>'Content-Encoding': 'gzip', 'Transfer-Encoding': 'chunked', 'Vary':
>'Accept-Encoding'}
>debug: b'<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body
>bgcolor="white">\r\n<center><h1>403
>Forbidden</h1></center>\r\n<hr><center>nginx/1.6.2</center>\r\n</body>\r\n</html>\r\n'
>    debug: GET https://dav.example.com/.well-known/caldav/
>debug: {'Content-Type': 'application/xml; charset=UTF-8', 'User-Agent':
>'vdirsyncer'}
>    debug: None
>    debug: Sending request...
>    debug: 404
>debug: {'Connection': 'keep-alive', 'Content-Type': 'text/html',
>'Date': 'Sun, 15 May 2016 08:53:45 GMT', 'Server': 'nginx/1.6.2',
>'Content-Encoding': 'gzip', 'Transfer-Encoding': 'chunked', 'Vary':
>'Accept-Encoding'}
>debug: b'<html>\r\n<head><title>404 Not Found</title></head>\r\n<body
>bgcolor="white">\r\n<center><h1>404 Not
>Found</h1></center>\r\n<hr><center>nginx/1.6.2</center>\r\n</body>\r\n</html>\r\n'
>    debug: Server does not support well-known URIs.
>    debug: PROPFIND https://dav.example.com/user/calendar.ics/
>debug: {'Content-Type': 'application/xml; charset=UTF-8', 'User-Agent':
>'vdirsyncer', 'Depth': 0}
>    debug: 
>    debug:         <d:propfind xmlns:d="DAV:">
>    debug:             <d:prop>
>    debug:                 <d:current-user-principal />
>    debug:             </d:prop>
>    debug:         </d:propfind>
>    debug:         
>    debug: Sending request...
>    debug: 403
>debug: {'Connection': 'keep-alive', 'Content-Type': 'text/html',
>'Date': 'Sun, 15 May 2016 08:53:45 GMT', 'Server': 'nginx/1.6.2',
>'Content-Encoding': 'gzip', 'Transfer-Encoding': 'chunked', 'Vary':
>'Accept-Encoding'}
>debug: b'<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body
>bgcolor="white">\r\n<center><h1>403
>Forbidden</h1></center>\r\n<hr><center>nginx/1.6.2</center>\r\n</body>\r\n</html>\r\n'
>    Unhandled exception occured.
>    Traceback (most recent call last):
>File
>"/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev48+ng139182e-py3.5.egg/vdirsyncer/storage/dav.py",
>line 142, in find_principal
>        return self.find_principal('')
>File
>"/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev48+ng139182e-py3.5.egg/vdirsyncer/storage/dav.py",
>line 156, in find_principal
>        data=body)
>File
>"/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev48+ng139182e-py3.5.egg/vdirsyncer/storage/dav.py",
>line 324, in request
>  return utils.http.request(method, url, session=self._session, **more)
>File
>"/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev48+ng139182e-py3.5.egg/vdirsyncer/utils/http.py",
>line 74, in request
>        r.raise_for_status()
>File "/usr/lib/python3/dist-packages/requests/models.py", line 840, in
>raise_for_status
>        raise HTTPError(http_error_msg, response=self)
>requests.exceptions.HTTPError: 403 Client Error: Forbidden for url:
>https://dav.example.com/user/calendar.ics/
>    
>    During handling of the above exception, another exception occurred:
>    
>    Traceback (most recent call last):
>File
>"/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev48+ng139182e-py3.5.egg/vdirsyncer/cli/utils.py",
>line 498, in _worker
>        func(wq=self)
>File
>"/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev48+ng139182e-py3.5.egg/vdirsyncer/cli/tasks.py",
>line 77, in discover_collections
>        rv = collections_for_pair(pair=pair, **kwargs)
>File
>"/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev48+ng139182e-py3.5.egg/vdirsyncer/cli/utils.py",
>line 201, in collections_for_pair
>        list_collections=list_collections))
>File
>"/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev48+ng139182e-py3.5.egg/vdirsyncer/cli/utils.py",
>line 313, in _collections_for_pair_impl
>        b_discovered = _discover_from_config(pair.config_b)
>File
>"/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev48+ng139182e-py3.5.egg/vdirsyncer/cli/utils.py",
>line 252, in _discover_from_config
>        return handle_storage_init_error(cls, config)
>File
>"/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev48+ng139182e-py3.5.egg/vdirsyncer/cli/utils.py",
>line 244, in _discover_from_config
>        discovered = list(cls.discover(**config))
>File
>"/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev48+ng139182e-py3.5.egg/vdirsyncer/storage/dav.py",
>line 202, in discover
>        for c in self.find_collections():
>File
>"/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev48+ng139182e-py3.5.egg/vdirsyncer/storage/dav.py",
>line 181, in find_collections
>        url = self.find_home()
>File
>"/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev48+ng139182e-py3.5.egg/vdirsyncer/storage/dav.py",
>line 165, in find_home
>        url = self.find_principal()
>File
>"/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev48+ng139182e-py3.5.egg/vdirsyncer/storage/dav.py",
>line 144, in find_principal
>        return self.find_principal(self.find_dav())
>File
>"/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev48+ng139182e-py3.5.egg/vdirsyncer/storage/dav.py",
>line 156, in find_principal
>        data=body)
>File
>"/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev48+ng139182e-py3.5.egg/vdirsyncer/storage/dav.py",
>line 324, in request
>  return utils.http.request(method, url, session=self._session, **more)
>File
>"/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev48+ng139182e-py3.5.egg/vdirsyncer/utils/http.py",
>line 74, in request
>        r.raise_for_status()
>File "/usr/lib/python3/dist-packages/requests/models.py", line 840, in
>raise_for_status
>        raise HTTPError(http_error_msg, response=self)
>requests.exceptions.HTTPError: 403 Client Error: Forbidden for url:
>https://dav.example.com/user/calendar.ics/
>    Discovering collections for pair my_contacts
>    debug: PROPFIND https://dav.example.com/user/addressbook.vcf/
>debug: {'Content-Type': 'application/xml; charset=UTF-8', 'User-Agent':
>'vdirsyncer', 'Depth': 0}
>    debug: 
>    debug:         <d:propfind xmlns:d="DAV:">
>    debug:             <d:prop>
>    debug:                 <d:current-user-principal />
>    debug:             </d:prop>
>    debug:         </d:propfind>
>    debug:         
>    debug: Sending request...
>    debug: 403
>debug: {'Connection': 'keep-alive', 'Content-Type': 'text/html',
>'Date': 'Sun, 15 May 2016 08:53:45 GMT', 'Server': 'nginx/1.6.2',
>'Content-Encoding': 'gzip', 'Transfer-Encoding': 'chunked', 'Vary':
>'Accept-Encoding'}
>debug: b'<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body
>bgcolor="white">\r\n<center><h1>403
>Forbidden</h1></center>\r\n<hr><center>nginx/1.6.2</center>\r\n</body>\r\n</html>\r\n'
>    debug: GET https://dav.example.com/.well-known/carddav/
>debug: {'Content-Type': 'application/xml; charset=UTF-8', 'User-Agent':
>'vdirsyncer'}
>    debug: None
>    debug: Sending request...
>    debug: 404
>debug: {'Connection': 'keep-alive', 'Content-Type': 'text/html',
>'Date': 'Sun, 15 May 2016 08:53:45 GMT', 'Server': 'nginx/1.6.2',
>'Content-Encoding': 'gzip', 'Transfer-Encoding': 'chunked', 'Vary':
>'Accept-Encoding'}
>debug: b'<html>\r\n<head><title>404 Not Found</title></head>\r\n<body
>bgcolor="white">\r\n<center><h1>404 Not
>Found</h1></center>\r\n<hr><center>nginx/1.6.2</center>\r\n</body>\r\n</html>\r\n'
>    debug: Server does not support well-known URIs.
>    debug: PROPFIND https://dav.example.com/user/addressbook.vcf/
>debug: {'Content-Type': 'application/xml; charset=UTF-8', 'User-Agent':
>'vdirsyncer', 'Depth': 0}
>    debug: 
>    debug:         <d:propfind xmlns:d="DAV:">
>    debug:             <d:prop>
>    debug:                 <d:current-user-principal />
>    debug:             </d:prop>
>    debug:         </d:propfind>
>    debug:         
>    debug: Sending request...
>    debug: 403
>debug: {'Connection': 'keep-alive', 'Content-Type': 'text/html',
>'Date': 'Sun, 15 May 2016 08:53:45 GMT', 'Server': 'nginx/1.6.2',
>'Content-Encoding': 'gzip', 'Transfer-Encoding': 'chunked', 'Vary':
>'Accept-Encoding'}
>debug: b'<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body
>bgcolor="white">\r\n<center><h1>403
>Forbidden</h1></center>\r\n<hr><center>nginx/1.6.2</center>\r\n</body>\r\n</html>\r\n'
>    Unhandled exception occured.
>    Traceback (most recent call last):
>File
>"/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev48+ng139182e-py3.5.egg/vdirsyncer/storage/dav.py",
>line 142, in find_principal
>        return self.find_principal('')
>File
>"/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev48+ng139182e-py3.5.egg/vdirsyncer/storage/dav.py",
>line 156, in find_principal
>        data=body)
>File
>"/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev48+ng139182e-py3.5.egg/vdirsyncer/storage/dav.py",
>line 324, in request
>  return utils.http.request(method, url, session=self._session, **more)
>File
>"/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev48+ng139182e-py3.5.egg/vdirsyncer/utils/http.py",
>line 74, in request
>        r.raise_for_status()
>File "/usr/lib/python3/dist-packages/requests/models.py", line 840, in
>raise_for_status
>        raise HTTPError(http_error_msg, response=self)
>requests.exceptions.HTTPError: 403 Client Error: Forbidden for url:
>https://dav.example.com/user/addressbook.vcf/
>    
>    During handling of the above exception, another exception occurred:
>    
>    Traceback (most recent call last):
>File
>"/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev48+ng139182e-py3.5.egg/vdirsyncer/cli/utils.py",
>line 498, in _worker
>        func(wq=self)
>File
>"/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev48+ng139182e-py3.5.egg/vdirsyncer/cli/tasks.py",
>line 77, in discover_collections
>        rv = collections_for_pair(pair=pair, **kwargs)
>File
>"/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev48+ng139182e-py3.5.egg/vdirsyncer/cli/utils.py",
>line 201, in collections_for_pair
>        list_collections=list_collections))
>File
>"/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev48+ng139182e-py3.5.egg/vdirsyncer/cli/utils.py",
>line 313, in _collections_for_pair_impl
>        b_discovered = _discover_from_config(pair.config_b)
>File
>"/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev48+ng139182e-py3.5.egg/vdirsyncer/cli/utils.py",
>line 252, in _discover_from_config
>        return handle_storage_init_error(cls, config)
>File
>"/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev48+ng139182e-py3.5.egg/vdirsyncer/cli/utils.py",
>line 244, in _discover_from_config
>        discovered = list(cls.discover(**config))
>File
>"/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev48+ng139182e-py3.5.egg/vdirsyncer/storage/dav.py",
>line 202, in discover
>        for c in self.find_collections():
>File
>"/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev48+ng139182e-py3.5.egg/vdirsyncer/storage/dav.py",
>line 181, in find_collections
>        url = self.find_home()
>File
>"/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev48+ng139182e-py3.5.egg/vdirsyncer/storage/dav.py",
>line 165, in find_home
>        url = self.find_principal()
>File
>"/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev48+ng139182e-py3.5.egg/vdirsyncer/storage/dav.py",
>line 144, in find_principal
>        return self.find_principal(self.find_dav())
>File
>"/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev48+ng139182e-py3.5.egg/vdirsyncer/storage/dav.py",
>line 156, in find_principal
>        data=body)
>File
>"/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev48+ng139182e-py3.5.egg/vdirsyncer/storage/dav.py",
>line 324, in request
>  return utils.http.request(method, url, session=self._session, **more)
>File
>"/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.10.1.dev48+ng139182e-py3.5.egg/vdirsyncer/utils/http.py",
>line 74, in request
>        r.raise_for_status()
>File "/usr/lib/python3/dist-packages/requests/models.py", line 840, in
>raise_for_status
>        raise HTTPError(http_error_msg, response=self)
>requests.exceptions.HTTPError: 403 Client Error: Forbidden for url:
>https://dav.example.com/user/addressbook.vcf/
>    error: 2 out of 2 tasks failed.
>
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/vdirsyncer/issues/448#issuecomment-219273970

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by legrostdg** [comment]
Mmh, sorry, I probably tested this outside of my lan, it seems to fail differently now. (Note that the previous error should probably be caught to have a better message, do you want me to open a new issue for this?) Here is the new error (latest vdirsyncer from git):

    $ vdirsyncer -v DEBUG discover
    debug: Using 1 maximal workers.
    Discovering collections for pair my_calendars
    debug: PROPFIND https://dav.example.com/user/calendar.ics/
    debug: {'User-Agent': 'vdirsyncer', 'Content-Type': 'application/xml; charset=UTF-8', 'Depth': 0
    debug: 
    debug:         <d:propfind xmlns:d="DAV:">
    debug:             <d:prop>
    debug:                 <d:current-user-principal />
    debug:             </d:prop>
    debug:         </d:propfind>
    debug:         
    debug: Sending request...
    debug: 207
    debug: {'Date': 'Mon, 30 May 2016 14:42:40 GMT', 'DAV': '1, 2, 3, calendar-access, addressbook, extended-mkcol', 'Server': 'nginx/1.6.2', 'Content-Type': 'text/xml', 'Connection': 'keep-alive', 'Content-Length': '324'}
    debug: b'<?xml version="1.0"?>\n<multistatus xmlns="DAV:">\n  <response>\n    <href>/user/calendar.ics/</href>\n    <propstat>\n      <prop>\n        <current-user-principal>\n          <href>/user/</href>\n        </current-user-principal>\n      </prop>\n      <status>HTTP/1.1 200 OK</status>\n    </propstat>\n  </response>\n</multistatus>\n'
    debug: PROPFIND https://dav.example.com/user/
    debug: {'User-Agent': 'vdirsyncer', 'Content-Type': 'application/xml; charset=UTF-8', 'Depth': 0}
    debug: 
    debug:     <d:propfind xmlns:d="DAV:" xmlns:c="urn:ietf:params:xml:ns:caldav">
    debug:         <d:prop>
    debug:             <c:calendar-home-set />
    debug:         </d:prop>
    debug:     </d:propfind>
    debug:     
    debug: Sending request...
    debug: 207
    debug: {'Date': 'Mon, 30 May 2016 14:42:42 GMT', 'DAV': '1, 2, 3, calendar-access, addressbook, extended-mkcol', 'Server': 'nginx/1.6.2', 'Content-Type': 'text/xml', 'Connection': 'keep-alive', 'Content-Length': '50'}
    debug: b'<?xml version="1.0"?>\n<multistatus xmlns="DAV:" />'
    error: The server returned something vdirsyncer doesn't understand. Error message: InvalidXMLResponse()
    error: While this is most likely a serverside problem, the vdirsyncer devs are generally interested in such bugs. Please report it in the issue tracker at https://github.com/pimutils/vdirsyncer/issues
    Discovering collections for pair my_contacts
    debug: PROPFIND https://dav.example.com/user/addressbook.vcf/
    debug: {'User-Agent': 'vdirsyncer', 'Content-Type': 'application/xml; charset=UTF-8', 'Depth': 0}
    debug: 
    debug:         <d:propfind xmlns:d="DAV:">
    debug:             <d:prop>
    debug:                 <d:current-user-principal />
    debug:             </d:prop>
    debug:         </d:propfind>
    debug:         
    debug: Sending request...
    debug: 207
    debug: {'Date': 'Mon, 30 May 2016 14:42:45 GMT', 'DAV': '1, 2, 3, calendar-access, addressbook, extended-mkcol', 'Server': 'nginx/1.6.2', 'Content-Type': 'text/xml', 'Connection': 'keep-alive', 'Content-Length': '327'}
    debug: b'<?xml version="1.0"?>\n<multistatus xmlns="DAV:">\n  <response>\n    <href>/user/addressbook.vcf/</href>\n    <propstat>\n      <prop>\n        <current-user-principal>\n          <href>/user/</href>\n        </current-user-principal>\n      </prop>\n      <status>HTTP/1.1 200 OK</status>\n    </propstat>\n  </response>\n</multistatus>\n'
    debug: PROPFIND https://dav.example.com/user/
    debug: {'User-Agent': 'vdirsyncer', 'Content-Type': 'application/xml; charset=UTF-8', 'Depth': 0}
    debug: 
    debug:     <d:propfind xmlns:d="DAV:" xmlns:c="urn:ietf:params:xml:ns:carddav">
    debug:         <d:prop>
    debug:             <c:addressbook-home-set />
    debug:         </d:prop>
    debug:     </d:propfind>
    debug:     
    debug: Sending request...
    debug: 207
    debug: {'Date': 'Mon, 30 May 2016 14:42:46 GMT', 'DAV': '1, 2, 3, calendar-access, addressbook, extended-mkcol', 'Server': 'nginx/1.6.2', 'Content-Type': 'text/xml', 'Connection': 'keep-alive', 'Content-Length': '50'}
    debug: b'<?xml version="1.0"?>\n<multistatus xmlns="DAV:" />'
    error: The server returned something vdirsyncer doesn't understand. Error message: InvalidXMLResponse()
    error: While this is most likely a serverside problem, the vdirsyncer devs are generally interested in such bugs. Please report it in the issue tracker at https://github.com/pimutils/vdirsyncer/issues
    error: 2 out of 2 tasks failed.

**Comment by untitaker** [comment]
@legrostdg There isn't a lot I can do when the server returns a "403 Forbidden" -- the error message is probably unnecessarily verbose but apart from that, vdirsyncer doesn't really have more information to show.

I'm rereading your config. Do I understand correctly that you have only one calendar and one addressbook? In that case, try setting `collections = null` for both pairs -- this should probably work around everything.

**Comment by legrostdg** [comment]
Regarding the 403 forbidden, vdirsyncer could catch the exception, couldn't it? The traceback could be provided with -v DEBUG, but it does not seem very polished to send that to the user by default. That's just what I suggested :-).

Regarding my config, I have multiple calendars and one addressbook. `collections = null` seems to work for contacts. I tried to manually specify `collections = ["calendar1", "calendar2"]` but it does not seem to work...

**Comment by legrostdg** [comment]
note that `collections = ["calendar1"]` does not work either.

**Comment by untitaker** [comment]
>Regarding the 403 forbidden, vdirsyncer could catch the exception, couldn't it? The traceback could be provided with -v DEBUG, but it does not seem very polished to send that to the user by default. That's just what I suggested :-).

I've been planning this for a while but never got around to it. Done with https://github.com/pimutils/vdirsyncer/commit/252f634c815048b786205db387880c79ea1b1956

>collections = null seems to work for contacts.

This is actually the correct way in your situation, I'd recommend to keep it like that.

>I tried to manually specify collections = ["calendar1", "calendar2"] but it does not seem to work...

Ok, let's try something different: Please show all `.props` files from Radicale.

**Comment by legrostdg** [comment]
> I've been planning this for a while but never got around to it. Done with 252f634

The errors look great now, thanks!

> Ok, let's try something different: Please show all .props files from Radicale.

    $ find /var/lib/radicale -name "*.props"
    /var/lib/radicale/collections/user/calendar.ics.props
    /var/lib/radicale/collections/user/calendar.ics/home.props
    /var/lib/radicale/collections/user/calendar.ics/work.props
    /var/lib/radicale/collections/user/calendar.ics/calendar.ics.props
    /var/lib/radicale/collections/user/calendar.ics/auie.props
    /var/lib/radicale/collections/user/addressbook.vcf/addressbook.vcf.props
    /var/lib/radicale/collections/user/addressbook.vcf.props
    /var/lib/radicale/collections/user/f2e2298d-cac3-4326-85b4-0330d59be671.props
    /var/lib/radicale/collections/.props
    /var/lib/radicale/collections/user.props
    /var/lib/radicale/collections.props

**Comment by untitaker** [comment]
I am not sure how you ended up with this structure, but as far as I understand Radicale doesn't properly support nested collections like that. While direct requests work, it completely fucks with listing calendars and addressbooks. At least in theory, because the RFCs don't allow nesting calendars within other calendars (same with addressbooks).

In particular, I think there is only one level of folder-depth allowed after `/user/`, and the collection type is only denoted by the file extension and the `.props` file. Your paths would look like:

    /user/home.ics
    /user/work.ics
    /user/addressbook.vcf
    ...

@lize: Is this sort of structure intentional? If I recall correctly, Radicale used to report `/user/calendar.ics/` as `addressbook-home-set`, so it's natural that clients attempt to create collections at that path.

**Comment by untitaker** [comment]
@legrostdg Any update on this?

**Comment by untitaker** [comment]
I'll close this due to inactivity, feel free to ping for updates.

**Comment by legrostdg** [comment]
Sorry, forgot about this :(. I'm waiting for a new release of radicale, to test this again. For now vdirsyncer and radicale seem to be incompatible.
